/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JLayeredPane;

/**
 *
 * @author Brwni
 */
public class JLayeredPane extends javax.swing.JFrame {

    /**
     * Creates new form JLayeredPane
     */
    public JLayeredPane() {
        initComponents();
        
        capas.setSelectedIndex(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LP1 = new javax.swing.JLayeredPane();
        defaultLayer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        palette = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        modal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        popup = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        drag = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        capas = new javax.swing.JComboBox<>();
        iconOnTop = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LP1.setBackground(new java.awt.Color(204, 204, 204));
        LP1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LP1.setForeground(new java.awt.Color(255, 255, 255));
        LP1.setOpaque(true);
        LP1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LP1MouseMoved(evt);
            }
        });
        LP1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        defaultLayer.setBackground(new java.awt.Color(255, 255, 0));
        defaultLayer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        defaultLayer.setForeground(new java.awt.Color(255, 255, 0));
        defaultLayer.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Default");
        jLabel1.setName("De"); // NOI18N

        javax.swing.GroupLayout defaultLayerLayout = new javax.swing.GroupLayout(defaultLayer);
        defaultLayer.setLayout(defaultLayerLayout);
        defaultLayerLayout.setHorizontalGroup(
            defaultLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultLayerLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        defaultLayerLayout.setVerticalGroup(
            defaultLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultLayerLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 84, Short.MAX_VALUE))
        );

        LP1.add(defaultLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        palette.setBackground(new java.awt.Color(255, 0, 204));
        palette.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Palette");
        jLabel3.setName("De"); // NOI18N

        javax.swing.GroupLayout paletteLayout = new javax.swing.GroupLayout(palette);
        palette.setLayout(paletteLayout);
        paletteLayout.setHorizontalGroup(
            paletteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paletteLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(22, 22, 22))
        );
        paletteLayout.setVerticalGroup(
            paletteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paletteLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        LP1.setLayer(palette, javax.swing.JLayeredPane.PALETTE_LAYER);
        LP1.add(palette, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        modal.setBackground(new java.awt.Color(0, 255, 255));
        modal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Modal");
        jLabel4.setName("De"); // NOI18N

        javax.swing.GroupLayout modalLayout = new javax.swing.GroupLayout(modal);
        modal.setLayout(modalLayout);
        modalLayout.setHorizontalGroup(
            modalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modalLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(24, 24, 24))
        );
        modalLayout.setVerticalGroup(
            modalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modalLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        LP1.setLayer(modal, javax.swing.JLayeredPane.MODAL_LAYER);
        LP1.add(modal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        popup.setBackground(new java.awt.Color(255, 0, 0));
        popup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Popup");
        jLabel2.setName("De"); // NOI18N

        javax.swing.GroupLayout popupLayout = new javax.swing.GroupLayout(popup);
        popup.setLayout(popupLayout);
        popupLayout.setHorizontalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        popupLayout.setVerticalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        LP1.setLayer(popup, javax.swing.JLayeredPane.POPUP_LAYER);
        LP1.add(popup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        drag.setBackground(new java.awt.Color(0, 255, 51));
        drag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Drag");
        jLabel5.setName("De"); // NOI18N

        javax.swing.GroupLayout dragLayout = new javax.swing.GroupLayout(drag);
        drag.setLayout(dragLayout);
        dragLayout.setHorizontalGroup(
            dragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dragLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(29, 29, 29))
        );
        dragLayout.setVerticalGroup(
            dragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dragLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 78, Short.MAX_VALUE))
        );

        LP1.setLayer(drag, javax.swing.JLayeredPane.DRAG_LAYER);
        LP1.add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\llean\\Downloads\\eye (3).png")); // NOI18N
        icon.setText("jLabel7");
        LP1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 70, -1));

        getContentPane().add(LP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 600, 390));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("Layered Panel");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 160, 40));

        capas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEFAULT_LAYER", "PALETTE_LAYER", "MODAL_LAYER", "POPUP_LAYER", "DRAG_LAYER" }));
        capas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                capasItemStateChanged(evt);
            }
        });
        capas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capasActionPerformed(evt);
            }
        });
        getContentPane().add(capas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, -1));

        iconOnTop.setText("Icono en Top");
        iconOnTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconOnTopActionPerformed(evt);
            }
        });
        getContentPane().add(iconOnTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconOnTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconOnTopActionPerformed
        if(iconOnTop.isSelected()) {
            LP1.moveToFront(icon);
        } else {
            LP1.moveToBack(icon);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_iconOnTopActionPerformed

    private void capasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capasActionPerformed
    
    private int getSelectedLayerValue() {
    String selected = (String) capas.getSelectedItem();
        return switch (selected) {
            case "DEFAULT_LAYER" -> LP1.DEFAULT_LAYER;
            case "PALETTE_LAYER" -> LP1.PALETTE_LAYER;
            case "MODAL_LAYER" -> LP1.MODAL_LAYER;
            case "POPUP_LAYER" -> LP1.POPUP_LAYER;
            case "DRAG_LAYER" -> LP1.DRAG_LAYER;
            default -> LP1.DEFAULT_LAYER;
        };
}
    
    private void capasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_capasItemStateChanged
        int pos = iconOnTop.isSelected() ? 0 : 1;
        LP1.setLayer(icon,getSelectedLayerValue(),pos);
        // TODO add your handling code here:
    }//GEN-LAST:event_capasItemStateChanged
    
    private void LP1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LP1MouseMoved
        int x = icon.getWidth();
        int y = icon.getHeight();
        icon.setLocation(evt.getX()-x, evt.getY()-y);
        // TODO add your handling code here:
    }//GEN-LAST:event_LP1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLayeredPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLayeredPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLayeredPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLayeredPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JLayeredPane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LP1;
    private javax.swing.JComboBox<String> capas;
    private javax.swing.JPanel defaultLayer;
    private javax.swing.JPanel drag;
    private javax.swing.JLabel icon;
    private javax.swing.JCheckBox iconOnTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel modal;
    private javax.swing.JPanel palette;
    private javax.swing.JPanel popup;
    // End of variables declaration//GEN-END:variables
}
